### ISSUE TITLE
Configure git completion by default

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#10]
Would be great to have git completion configured by default in all accounts.

https://git-scm.com/book/en/v1/Git-Basics-Tips-and-Tricks
https://cornel.co/article/configure-git-completion-ubuntu

Simply sourcing /etc/bash_completion.d/git-prompt was not sufficient

```
ls -al /etc/bash_completion.d/git-prompt
-rw-r--r-- 1 root root 439 Dec  1  2016 /etc/bash_completion.d/git-prompt

```

**Comment by ogrand** [comment]
Git completion is now available with the persistant user script "initenv.sh" outside orange-cf-bosh-cli release

**Comment by ogrand** [comment]
Git completion is now available with the persistant user script "initenv.sh" outside orange-cf-bosh-cli release
