### ISSUE TITLE
Svcat binary is corrupted

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#105]
In image ghcr.io/orange-cloudfoundry/orange-cf-bosh-cli@sha256:4b1727c85a24fb11a3d43decc08a4209594c8f0b8a8c9fe69b1e5a6e1bb3a4a4 the downloaded svcat binary seems invalid:

```
root@...:~# svcat completion bash
/usr/local/bin/svcat: line 1: syntax error near unexpected token `<'
/usr/local/bin/svcat: line 1: `﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.'

root@...:~# cat /usr/local/bin/svcat
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
RequestId:44f6f173-401e-0105-303c-e88a43000000
Time:2022-10-25T06:41:23.1269215Z</Message></Error>

root@...:~# ls -al /usr/local/bin/svcat
-rwxr-xr-x 1 root root 246 Oct 25 06:41 /usr/local/bin/svcat
```

May be the installation instructions at https://github.com/orange-cloudfoundry/orange-cf-bosh-cli/blob/a802facc4d9cff1635ffc98b42d07a3615be4f38/Dockerfile#L127 could detect an incorrect binary

## Workaround

```sh
sudo -i
export https_proxy=http://system-internet-http-proxy.internal.paas:3128
SVCAT_VERSION="0.3.1"; curl -sSLo /usr/local/bin/svcat "https://download.svcat.sh/cli/v${SVCAT_VERSION}/linux/amd64/svcat"
```

**Comment by ogrand** [comment]
The pb comes from svcat github repository has been archived by the owner, and is now read-only.
Trying to donwload binary file trigers following error message:
___This request is not authorized to perform this operation___
