### ISSUE TITLE
display-last-k9s-screen alias

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#107]
## Expected behavior

As a k9s user
* in order to easily leverage the k9s screen files produced by CTRL-s short cut and saved in /tmp/k9s-screens-bosh/
* I need an alias that searches the latest file created and displays uit

## Current behavior

Copy paste a command such as

```
#Credit https://stackoverflow.com/a/23034261/1484823
F=$(find /tmp/k9s-screens-bosh/ -type f -printf "%T@ %p\n" | sort -n | cut -d' ' -f 2- | tail -n 1); printf "latest k9s screen is: \n$(ls -al $F)\n\nPress Enter to display it or Ctrl-C to abort"; read;
 less $F;
```

**Comment by ogrand** [comment]
Done with latest version
