### ISSUE TITLE
add yq 

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#112]
## Expected behavior

As a bosh cli user
In order to manipulate yml such as advised into https://weaveworks.github.io/tf-controller/how_to/backup_and_restore_a_Terraform_state/#restore-the-tfstate
I need the yq binary installed

## References 

https://github.com/mikefarah/yq#on-ubuntu-1604-or-higher-from-debian-package

## workaround

```bash
curl -LO https://github.com/mikefarah/yq/releases/download/v4.30.8/yq_linux_amd64.tar.gz
tar xvfz yq_linux_amd64.tar.gz 
sudo mv ./yq_linux_amd64 /usr/bin/yq
```

**Comment by ogrand** [comment]
Available in latest release
