### ISSUE TITLE
Add vcluster cli

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#114]
## expected behavior
As a cli user
in order to kubectl connect into a vcluster
I need the vcluster cli to be installed with completion enabled

https://www.vcluster.com/docs/getting-started/setup

## workaround

```
curl -L -o vcluster "https://github.com/loft-sh/vcluster/releases/latest/download/vcluster-linux-amd64" && sudo install -c -m 0755 vcluster /usr/local/bin && rm -f vcluster
source <(vcluster completion bash)
```

**Comment by ogrand** [comment]
Available in latest release
