### ISSUE TITLE
log-uaac is missing ops-routing uaa

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#115]
## expected behavior

As a paas-templates operator
in order to inspect UAA clients from micro-depls/ops-routing
I need to be able to get a uaac context within `log-uaac`

## current behavior

```
$ log-uaac
Target UAA :

1 : micro-bosh
2 : bosh-master
3 : bosh-ops
4 : bosh-coab
5 : bosh-remote-r2
6 : bosh-remote-r3
7 : cf (master-depls/cf)
```

**Comment by ogrand** [comment]
Available in latest release
