### ISSUE TITLE
Add ocm cli

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#116]
## expected behavior

As a cli user
in order to lookup a openshift managed instance into 
I need ocm cli to be installed, see https://github.com/openshift-online/ocm-cli/ and completion configured

## workaround

```
curl -LO https://github.com/openshift-online/ocm-cli/releases/download/v0.1.65/ocm-linux-amd64
chmod +x ocm-linux-amd64 
mv ocm-linux-amd64 ocm
source <(./ocm-linux-amd64 completion bash)
./ocm version
```

**Comment by ogrand** [comment]
Available in latest release
