### ISSUE TITLE
Add alias to clone paas-templates and secrets repo

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#119]
## Expected behavior

As a paas-templates operator / author
In order to perform paas-templates upgrades
In order to run admin commands from paas-templates
I need a fresh clone of the paas-templates associated with the current platform git remote
I need a fresh clone of the secret repo associated with the current platform git remote
I need a fresh clone of the gitops repo associated with the current platform git remote

with an automated alias

## Current behavior/workaround

manual commands
```
mkdir bosh
cd bosh
git clone $(credhub-get ...) templates
git clone $(credhub-get ...) secrets
# configure password credentials cache
# configure email address
git config ...
or 
init-git.sh
```

**Comment by ogrand** [comment]
Done with latest release
