### ISSUE TITLE
add gh cli

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#120]
## Expected behavior

As a paas-templates contributors
In order to automate handling of PRs such as renovate and invoke `paas-templates/bin/list-renovate-prs-with-multiple-commits.bash`
I need the github cli to be installed and configured with auto completion

## Workaround

Manually install gh cli linux binary, see https://github.com/cli/cli#linux--bsd
\+ `gh auth`
\+ `source <(gh completion -s bash)`

**Comment by ogrand** [comment]
Done with latest image
