### ISSUE TITLE
add jwt-cli

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#128]
### Expected 

As a paas-templates operator
In order to easily inspect K8S service account tokens encoded as JWT tokens
I need a tool to decode JWT tokens safely/productively without potentially leaking the key with copy/pastes

### References

https://github.com/mike-engel/jwt-cli

### Workaround

```
curl -LO https://github.com/mike-engel/jwt-cli/releases/download/5.0.3/jwt-linux.tar.gz
tar xvfz jwt-linux.tar

$ k get secrets/paas-templates-admin-token-2rtbp -o jsonpath='{.data.token}' | base64 -d | jwt decode - -j
{
  "header": {
    "alg": "RS256",
    "kid": "[....]"
  },
  "payload": {
    "iss": "kubernetes/serviceaccount",
    "kubernetes.io/serviceaccount/namespace": "default",
    "kubernetes.io/serviceaccount/secret.name": "paas-templates-admin-token-2rtbp",
    "kubernetes.io/serviceaccount/service-account.name": "paas-templates-admin",
    "kubernetes.io/serviceaccount/service-account.uid": "[....]",
    "sub": "system:serviceaccount:default:paas-templates-admin"
  }
}
```

Note: https://stackoverflow.com/questions/43867440/whats-the-meaning-of-the-kid-claim-in-a-jwt-token
> kid is an optional header claim which holds a key identifier, particularly useful when you have multiple keys to sign the tokens and you need to look up the right one to verify the signature.

### online 

Copy/paste token into https://jwt.io/

**Comment by ogrand** [comment]
Done with latest release
