### ISSUE TITLE
k9s plugin to purge namespace by deleting finalizer

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#135]
## Expected

as an orange-cf-bosh-cli user,
in order to force the deletion of a namespace
I need a k9s plugin to do so

## Workaround

```
# git clone paas templates repo
~/bosh/template/admin/delete-k8s-ns.sh
```

## Other tested alternatives

https://github.com/xcoulon/kubectl-terminate 

Limitations:
- no new release since 2021
- not yet published through krew https://github.com/xcoulon/kubectl-terminate/issues/16
- missing verbose output
- does list existing namespace

**Comment by ogrand** [comment]
Should be done with command like:

```
NAME="<namespace to use>"
kubectl get ns $NAME -o json | tr -d '\n' | sed -e 's/\"finalizers\": \[[^]]\+\]/\"finalizers\": []/' | kubectl replace --raw /api/v1/namespaces/$NAME/finalize -f -
```

But finally this issue is a little bit dangerous for ops users who may delete namespace by error.
Closed the issue.
