### ISSUE TITLE
add gitlab cli

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#137]
## Expected

As a paas-templates contributor
In order to interact with gitlab for PRs, Issues, users
I need to use gitlab ci

## Workaround

```bash
wget https://gitlab.com/gitlab-org/cli/-/releases/v1.31.0/downloads/glab_1.31.0_Linux_x86_64.deb
sudo dpkg -i glab_1.31.0_Linux_x86_64.deb
source <(glab completion bash)
#create an access token with at least api access within gitlab user preference -> Access Tokens
glab auth login -h <gitlab_hostname>
git clone <url>
glab issue list --label spike 
```

## References

https://gitlab.com/gitlab-org/cli
https://gitlab.com/gitlab-org/cli/-/blob/main/docs/installation_options.md

**Comment by ogrand** [comment]
Add cli and completion to latest release
