### ISSUE TITLE
Docker file security best practice: use COPY instead of ADD

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#141]
Dockers best practices documentation recommends using COPY instead of ADD:

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy
> ADD or COPY
> 
> Although ADD and COPY are functionally similar, generally speaking, COPY is preferred. That’s because it’s more transparent than ADD. COPY only supports the basic copying of local files into the container, while ADD has some features (like local-only tar extraction and remote URL support) that are not immediately obvious. Consequently, the best use for ADD is local tar file auto-extraction into the image, as in ADD rootfs.tar.xz /.

See related security warning in crossplane security audit 
https://github.com/crossplane/crossplane/blob/master/security/ADA-security-audit-23.pdf

![image](https://github.com/orange-cloudfoundry/orange-cf-bosh-cli/assets/4748380/07a2148a-06b2-41a0-baf1-c89e6f75bd56)

**Comment by ogrand** [comment]
Done with latest release
