### ISSUE TITLE
Add aquasecurity/kubectl-who-can

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#142]
## Expected behavior

As a paas-templates operator, 
in order to review/inspect rbac,
I need proper tooling such as https://github.com/aquasecurity/kubectl-who-can

## Observed behavior

Previous tool #108 

```
$ rbac-tool who-can patch compositeresourcedefinitions.apiextensions.crossplane.io 
Failed to run program - memory budget exceeded (6:24)
 |        {  .Verb     in [Verb, "*"] and 
 | .......................^
```

See pending upstream issue https://github.com/alcideio/rbac-tool/issues/78

## workaround

```
kubectl krew install who-can
kubectl who-can create compositeresourcedefinitions.apiextensions.crossplane.io
```

**Comment by ogrand** [comment]
Done with latest release
