### ISSUE TITLE
Use color code in username@env prompt 

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#143]
## Expected behavior

As paas-templates contributor
In order to avoid confusion between integration, preprod, and prod
I need the color code used in portal (int=blue, preprod=green prod=red) to be applied to the prompt prefix username@env

## Current behavior

The  prompt prefix username@env is always displayed in green

**Comment by ogrand** [comment]
Done with latest release
