### ISSUE TITLE
Add --verbose option to init-mc.sh to troubleshoot hanging mc commands

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#145]
## Expected behavior

As a bastion user,
In order to troubleshoot `init-mc.sh` which silently hangs in a command
I need an option to turn on `set -x` bash traces + pass the `--debug` flag to `mc config` command

## Workaround

```
vi /data/shared/a-user/bosh/template/admin/init-mc.sh
# add `set -x`
# pass `--debug` flag to `mc config` command
```

**Comment by ogrand** [comment]
No add debug option to scripts, but you can set debug traces when running scripts like

```
$ bash -x <script to run>
```
