### ISSUE TITLE
Extend color scheme to tmux bar

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#151]
### Expected

As an operator using tmux
In order to avoid confusing prod with non prod
I need tmux config to color the tmux bar with the default per environment color

### Current

The default tmux green status bar color is used

### Workaround

Locally configure a tmux status bar in each user profile
https://unix.stackexchange.com/questions/60968/tmux-bottom-status-bar-color-change

**Comment by ogrand** [comment]
Done in latest release

**Comment by ogrand** [comment]
Done with latest version
