### ISSUE TITLE
Add libldap-common to configure ldap tls client to fetch default ca certs in /etc/ssl/certs/ca-certificates.crt

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#153]
## Expected behavior

`libldap-common` package should be installed

As mentionned into https://serverfault.com/a/1149381/989048

> note that gnutls-cli automatically loads the operating system's Certificate Authorities, but ldapsearch only loads them if properly configured.
> 
> This is the reason why [ForJ9's answer](https://serverfault.com/a/1136224/1064310) recommends installing libldap-common. It is a Debian package containing only a single file /etc/ldap/ldap.conf (and some docs) which contains only a single uncommented line:
> 
> TLS_CACERT      /etc/ssl/certs/ca-certificates.crt

## Observed behavior

```bash
ldapwhoami -v -d -1 -Z -H ldaps://... -D ... -w password
#> TLS: peer cert untrusted or revoked (0x42)                                                               
#> TLS: can't connect: (unknown error code).                                                                
#> ldap_err2string                                                                                          
#> ldap_start_tls: Can't contact LDAP server (-1)                                                           
#>         additional info: (unknown error code)     
```

## Workaround 1

```bash
sudo -i
# declare http proxy env varas
apt-get update
apt-get install libldap-common
```

## Workaround 2

```bash
ldapwhoami -v -d -1 -Z -H ldaps://...  -o tls_cacert=/etc/ssl/certs/ca-certificates.crt -D ... -w password
```

**Comment by ogrand** [comment]
Add with latest release
