### ISSUE TITLE
Prevent k9s plugins with write actions to be enabled in read-only mode

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#159]
## Expected behavior

As an operator, in order to avoid acting on production by error, I need k9s plugins that perform modifications to be enabled by default, by setting dangerous=true flag in their plugin

See https://github.com/derailed/k9s/pull/2786/files

## Current behavior

Dangerous mode not yet set in https://github.com/orange-cloudfoundry/orange-cf-bosh-cli/blob/master/tools/k9s-plugins.yaml for the following commands:
* reconcile-*
* toggle-*
* debug
* cnpg-psql

**Comment by ogrand** [comment]
Done with latest version
