### ISSUE TITLE
Add tmux completion

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#161]
## Expected behavior

* As an operator,
* In order to use tmux cli to interact with tmux 
* I need to use tmux completion available at https://github.com/imomaliev/tmux-bash-completion/blob/master/completions/tmux

## Workaround

```bash
proxy -i 

curl -LO https://github.com/imomaliev/tmux-bash-completion/blob/master/completions/tmux
# Review source code carefully before executing
less tmux
source tmux
```

**Comment by ogrand** [comment]
Done with latest release
