### ISSUE TITLE
get-vm-info to display nsx segments

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#163]
## Expected behavior

As a paas-templates operator,
In order to diagnose network misconfiguration in bosh 
I need to display the network segments attached to a vm

## Current behavior

get-vm-info is great but not yet displaying network segments

## Workaround

```
govc vm.info -json ${vm_name} | jq '.virtualMachines[0].guest.net
```

**Comment by ogrand** [comment]
Done with latest version
