### ISSUE TITLE
init-git incorrectly clones coa into /bosh/gitops repo

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#166]
See https://github.com/orange-cloudfoundry/orange-cf-bosh-cli/blob/a4a4d3cb47fff0856d3be6420a00996d8a24e7ce/tools/scripts/init-git.sh#L109
and original request https://github.com/orange-cloudfoundry/orange-cf-bosh-cli/issues/125

**Comment by ogrand** [comment]
Done with latest release
