### ISSUE TITLE
Improve initial password change experience

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#2]
Currently, on initial logging, users are displayed the following messages, and have to create themselves the ~/.ssh directory with proper permissions, and assign the proper permissions to the ~/.ssh/authorized_keys file. Also the default file permission need to be fixed on the ~/.ssh/authorized_keys file to be accepted.

``` 
For security reasons:
  1. Add you RSA private key into ~/.ssh/authorized_keys,
  2. Before logout, ensure you can log with private/public key authentication,
  3. Password authentication become disabled.
  4. If you don't do this, your password will be resetted at container restart or update.

$ umask 
0022

```

Suggested improvements:
- have the ~/.ssh created with the proper permissions by default
- refine the comment to display "chmod 700 ~/.ssh/authorized_keys" or fix default umask

**Comment by gberche-orange** [comment]
As discussed within team standup on Oct 7th, a better approach would be to inject the authorized public key at the time the account is created, and remove the temporary password feature.

The authorized public key would be passed as a property in the [bosh manifest](https://github.com/orange-cloudfoundry/orange-cf-bosh-cli#how-to-use-it-using-docker-bosh-release) and get propagated to the docker container through an environment variable.

**Comment by fbonelle** [comment]
It's now possible to add your public key to the container threw an environment variable.

To launch the container, issue: docker run --name cf-bosh-cli -d -p 2222:22 -v /home/bosh -v /data -e "SSH_PUBLIC_KEY=< put here your ssh-rsa public key >" 

Your ssh public key will be pushed into ~/.ssh/authorized_keys out of the box.

**Comment by gberche-orange** [comment]
See https://github.com/orange-cloudfoundry/orange-cf-bosh-cli/commit/3e70b3fbef43a5d4f571f701630c2a907391be90#commitcomment-19374279
