### ISSUE TITLE
add kubernetes cli s

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/orange-cf-bosh-cli#22]
As Cloudfoundry now support K8S with Cloudfoundry Container Runtime, operators need the kubectl cli in the bastion container
cc @obeyler

**Comment by poblin-orange** [comment]
+ add helm cli https://github.com/kubernetes/helm/releases/tag/v2.8.1

**Comment by ogrand** [comment]
resolved in 2.1.5
