### ISSUE TITLE
the docker cli should include terraform cloudfoundry plugin

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/orange-cf-bosh-cli#3]
There is a new terraform plugin for cloudfoundry .
We should include terraform core + cloudfoundry plugin in the base cf-bosh-cli image (derivated image could include iaas specific plugins, like openstack)
https://github.com/orange-cloudfoundry/terraform-provider-cloudfoundry

**Comment by ogrand** [comment]
Available with 2.0.4 release
