### ISSUE TITLE
Update credhub to 2.1.0

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#30]
https://github.com/cloudfoundry-incubator/credhub-cli/releases/tag/2.1.0

Hoping to benefit from CREDHUB_DEBUG enviroment variable support which is not working in 1.7.7.

> CredHub CLI v2 is now backwards compatible with CredHub server versions 1.9 and 1.7. A few commands no longer work (documented below); if you rely on these behaviors, please use a 1.x version of the CLI.
>
>    The --no-overwrite flag has been removed from the set command.
>    The --find-all-paths flag has been removed from the find command.

**Comment by ogrand** [comment]
Done in 2.1.24 release
