### ISSUE TITLE
Include experimental uaa golang cli

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#31]
Experimental binaries are for now available at https://github.com/starkandwayne/uaa-cli-releases/releases/download/v0.0.1/uaa-linux-amd64
The ruby uaac gem would remain until the uaa golang client becomes GA

See related https://github.com/cloudfoundry-incubator/uaa-cli/issues/4 for pending official binaries
See related cf summit basel slides at https://schd.ws/hosted_files/cfseu18/07/A%20new%20golang%20CLI%20for%20UAA%20-%20Jennifer%20Hamon.pdf

**Comment by ogrand** [comment]
Done in 2.1.24 release
