### ISSUE TITLE
Add a logout_uaa command

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#36]
As a bosh-cli user, in order to be able to consecutively log into multiple uaa servers, and possibly log out my current shell session from uaa, I would need a command similar to `logout_uaac`

Currently, performing multiple `log_uaac` commands with different targets fails with 

```
error response:
{
  "error": "unauthorized",
  "error_description": "Bad credentials"
}
attempt to get token failed
```

**Comment by ogrand** [comment]
Closed in 1.2.30
