### ISSUE TITLE
Refine mc command with host config

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#38]
As an operator, in order to connect to minio using mc, I need the host to be configured when I run the mc command

Suggesting to add similar command for each minio host in paas-templates
```
    mc config host add minio-private-s3  http://private-s3.internal.paas:9000 private-s3 `credhub get -n /micro-bosh/minio-private-s3/s3_secretkey -j | jq .value -r`
```

**Comment by ogrand** [comment]
Close in 2.1.35 release
