### ISSUE TITLE
Add mc autocompletion

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#39]
As a minio operator, in order to productively interact with minio cli, I need autocompletion on commands, and possibly files

Minio seems to have basic completion on commands.

See https://github.com/minio/mc#shell-autocompletion and https://github.com/minio/mc/pull/2095/files

Suggesting to pair with @gberche-orange and @o-orand on this, as this might require some futher investigation related to mc issues https://github.com/minio/mc/issues?utf8=%E2%9C%93&q=is%3Aissue++complete+

**Comment by ogrand** [comment]
Close in 2.1.35 release
