### ISSUE TITLE
Bosh command not found

### ISSUE THREAD

**Issue by T0FFF** [orange-cloudfoundry/orange-cf-bosh-cli#4]
Hello,
After redeploy the orange-cf-bosh-cli, I don't have the bosh-cli installed in my environment.
"/bin/bash -l -c "http_proxy=$http_proxy https_proxy=$https_proxy gem install bosh_cli --no-ri --no-rdoc -v ${bosh_cli_version}" && \" seems to be ok but the link in the $PATH (/usr/local/bin ?) is not created.

**Comment by poblin-orange** [comment]
hello @T0FFF 
im not sure you can upgrade the bosh-cli inside the container.
You lost it after a stemcell change, or a docker image version change ?

**Comment by T0FFF** [comment]
Thanks for your reply, I'm sorry Pierre, I understood my mistake. I use the zsh shell but my PATH variable was not properly configured (I have a default PATH /usr/local/bin/:/bin...).
When installing bosh with "gem install..." the PATH variable contains "/usr/local/rvm/gems/ruby-2.3.3/bin ...", with apt-get bosh the binary is under /usr/local/bin/.
I have updated my variable under zsh ;)
