### ISSUE TITLE
Add K8S helm login helpers

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#41]
Expected:

As a paas-template operator, in order to act onto K8S helm chart (including applying release notes), I need an efficient way to login into K8S helm cli

Observed:

naive cli usage lacks default login

```bash
helm list
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp 127.0.0.1:8080: connect: connection refused
```

/CC @obeyler

**Comment by obeyler** [comment]
I link this issue to #40 as helm and kubecl use the same config file located into .kubo/config

**Comment by ogrand** [comment]
Close in 2.1.35 release
