### ISSUE TITLE
Provide bash function to fetch credhub value

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#43]
As a bosh-cli user, in order to easily publicly share and execute commands that depend on credhub value (such as ops domain, credentials), I need a concise syntax to fetch a credhub plain value

e.g. in https://github.com/orange-cloudfoundry/paas-templates/issues/124#issuecomment-496960482

``
mc config host add minio-private-s3  http://private-s3.internal.paas:9000 `credhub get -n /micro-bosh/minio-private-s3/s3_accesskey -j | jq .value -r`
``

would become

``
mc config host add minio-private-s3  http://private-s3.internal.paas:9000 `credhub_get /micro-bosh/minio-private-s3/s3_accesskey`
``

**Comment by ogrand** [comment]
Close in 2.1.35 release
