### ISSUE TITLE
Configure bash prompt to display current git branch

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#44]
As a paas-template operator, in order to apply requested git steps on bosh-cli, I need the bash prompt to hint about current git branch status

See https://coderwall.com/p/pn8f0g/show-your-git-status-and-branch-in-color-at-the-command-prompt as inspiration

**Comment by ogrand** [comment]
Close in 2.1.35 release
