### ISSUE TITLE
proxy helper improvements

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#49]
The `proxy` helper is a productive way to toggle http proxy in bosh-cli while keeping a visual feedback that proxy is enabled. 

Here are additional minor potential improvement suggestions
- export a `no_proxy` environment variable to exclude intranet and paass-template deployments that could be accidentally proxied by the internet proxy. This would make need to toggle off the proxy less frequent. The syntax supported by bosh cli is documented at https://bosh.io/docs/cli-global-flags/#http-proxy
   - export no_proxy="current-cidr,192.168.0.0/16,172.17.0.0/16,internal.paas,intranet_tld"
where `current-cidr` can be obtained with `ip route show | grep / | awk '{print $1}'`
where `intranet_tld` can be obtained with `credhub get -n /secrets/osb_interco/osb_domain -j | jq -r .value | sed 's/.*\././g'` (e.g. myintranettld )

- rename the alias into `toogle-proxy` to express the behavior that the cmd should be called repetitively to toggle/untoggle

**Comment by ogrand** [comment]
Available on future 2.1.37 release
- Add no_proxy and NO_PROXY env vars with internal range/domains and intranet domains
- Add `toggle-proxy` alias but keep old `proxy` on
