### ISSUE TITLE
log-bosh to automate fetching admin secrets 

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#50]
As a paas-templates operators, in order to speed up recovery during outages or openldap downtimes (see https://github.com/orange-cloudfoundry/paas-templates/issues/99), I need to be able to login quickly in bosh directors using admin credentials.

bosh directors credentials can be fetched from credhub using clientid/client-secrets provisionned for bosh directors. See https://github.com/orange-cloudfoundry/paas-templates/issues/99#issuecomment-518681045

We are lacking a solution when credhub is down, as not all directors secrets are available in secrest git repo

**Comment by ogrand** [comment]
processed in version 2.1.38
