### ISSUE TITLE
Zsh for better prompt/cli

### ISSUE THREAD

**Issue by jvizier** [orange-cloudfoundry/orange-cf-bosh-cli#55]
Hello i made a env based on zsh and i need some packages as requirements :

Here is what i use :

sudo apt-get install zsh
sudo apt-get install ruby ruby-dev locales
sudo locale-gen en_US.UTF-8
gem install colorls --user

At minima i will need 

sudo apt-get install zsh
sudo apt-get install locales
sudo locale-gen en_US.UTF-8

Thx

**Comment by ogrand** [comment]
processed in version 2.1.38
