### ISSUE TITLE
Add CF CLI V7 beta

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#59]
As a paas-templates operator, in order to leverage CF metadata used in osb-cmdb (https://github.com/orange-cloudfoundry/osb-cmdb-spike/issues/10#issuecomment-567967267), I need the latest CF CLI V7 installed v7.0.0-beta.27 or later, see https://github.com/cloudfoundry/cli/#downloading-the-v7-beta-cli for installation instructions.

```
$ cf7 --version
cf7 version 7.0.0-beta.27+1ea93d838.2019-11-04
```

The completion should also be enabled on `cf7` command

**Comment by ogrand** [comment]
processed in version 2.1.38
