### ISSUE TITLE
home directory lost on container restart

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/orange-cf-bosh-cli#6]
Seem we loose all direct user homedir content file when the container is restarted, when deployed as docker bosh release. Should provide guidance on how to deploy a usable docker bosh cli without user data loss

**Comment by ogrand** [comment]
Users have a persistant directory on "/home/bosh/shared/<user>" with ".bashrc" automatically run on user connexion. Directory and ".bashrc" are created with "/home/bosh/shared/tools/initenv.sh" (outside orange-cf-bosh-cli)
