### ISSUE TITLE
Add svcat cli

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#64]
As a service author and osb-cmdb operator
* in order to interact with service catalog in K8S clusters
* I need the svcat cli in the bosh cli
* and I need the completion on svcat to be setup 
* and I need the kubectrl svcat plugin cli

See svcat cli installation step at https://svc-cat.io/docs/install/#installing-the-service-catalog-cli for linux, including completion running `source <(svcat completion bash)`

See Kubectl svcat plugin install at https://svc-cat.io/docs/cli/#plugin-mode

relates to https://github.com/orange-cloudfoundry/paas-templates/issues/751

Note: svcat cli uses kubectl configuration set by `log-k8s`, no need for additionnal config.

**Comment by ogrand** [comment]
Done with latest version
