### ISSUE TITLE
Add kustomize cli

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#68]
As a K8S template author
* in order to leverage community K8S spec files designed to be post-processed using kustomize, and troubleshoot kustomize related scripts
* I need the kustomize cli to be on the bosh-cli

Details 
* installation from precompiled binaries https://kubernetes-sigs.github.io/kustomize/installation/binaries/ currently pointing to https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv3.8.2

/CC @obeyler

**Comment by ogrand** [comment]
Fixed in 2.1.42 release
