### ISSUE TITLE
Add current k8s cluster and namespace to prompt

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#72]
### Expected behavior

* As a paas-templates operator
* In order to avoid running kubectl commands in the wrong K8S cluster or namespace
* I need to have a prompt reminding me in which K8S cluster and namespace my current kubectl config contain

See https://github.com/jonmosco/kube-ps1 and its demo below

![kube-ps1 demo](https://raw.githubusercontent.com/jonmosco/kube-ps1/master/img/kube-ps1.gif)

### Observed behavior

current promt (PS1) is only username@paas-templates-platform-name

**Comment by ogrand** [comment]
Set with next release
