### ISSUE TITLE
Add current bosh director and deployment to prompt

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#73]
### Expected behavior

* As a paas-templates operator
* In order to avoid running `bosh` commands in the wrong bosh director or deployment
* I need to have a prompt reminding me in which wrong bosh director or deployment my current bosh config contain

See https://github.com/psycofdj/xtdbash#bosh for inspiration

![psycofdj/xtdbash bosh prompt](https://raw.githubusercontent.com/psycofdj/xtdbash/master/docs/bosh.gif)

### Observed behavior

current promt (PS1) is only username@paas-templates-platform-name

**Comment by ogrand** [comment]
Set with next release
