### ISSUE TITLE
add govc completion

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#75]
## Expected behavior

* As a paas-templates operator
* in order to ease usage of `govc` cli
* I need the built-in completion available at https://github.com/vmware/govmomi/blob/9054158bb458f8c383422253709b56dc318ba2c0/scripts/govc_bash_completion to be configured within the bosh-cli environmeznt

## Observed behavior

completion does not work for `govc` command

**Comment by ogrand** [comment]
Done with latest release
