### ISSUE TITLE
K9S get-all plugin

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#77]
### Expected behavior

* As a paas-templates operator 
* In order to list/search/filter all resources in a k8s cluster
* I need support for the [get-all k9s plug-in](https://github.com/derailed/k9s/blob/master/plugins/get-all.yml)
   * listed as an alternative to future native k9s support https://github.com/derailed/k9s/issues/949

### References and implementation steps
 
* [ ] Configure k9s plugins. https://k9scli.io/topics/plugins/ `$XDG_CONFIG_HOME/k9s/plugin.yml`
* [ ] Add [get-all k9s plug-in](https://github.com/derailed/k9s/blob/master/plugins/get-all.yml)
   * [ ] Include https://github.com/corneliusweig/ketall
      * [ ] directly with https://github.com/corneliusweig/ketall/releases
      * [ ] or through krew: `Krew is the plugin manager for kubectl command-line tool` https://krew.sigs.k8s.io/
         * [ ] Include krew in docker image https://krew.sigs.k8s.io/plugins/
            * [ ] https://krew.sigs.k8s.io/docs/user-guide/setup/install/
            * [ ] `kubectl krew install get-all`

**Comment by ogrand** [comment]
update in lalest release
