### ISSUE TITLE
Add krew kubectl package manager

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#78]
### Expected behavior

* As a paas-templates operator
* In order to discover and test new kubectl plugins easily
* I need to use krew: `Krew is the plugin manager for kubectl command-line tool` https://krew.sigs.k8s.io/

### Observed behavior

```
$ krew
-bash: krew: command not found
```

**Comment by ogrand** [comment]
update in latest release
