### ISSUE TITLE
Add completion for kustomize cli

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#83]
## Expected behavior

As a paas-template author
* in order to speed up use of kustomize cli
* I need the completion to be configured

See https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/docs/commands/completion.md

## workaround

```
source <(kustomize completion bash)
```

**Comment by ogrand** [comment]
Set in latest release
