### ISSUE TITLE
turn off vim ill yaml formating

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#84]
# expected behavior

* as a paas-templates author
* in order to paste yaml in vim
* I need vim to not break the yaml indentation

# observed behavior

breaks yaml formatting

# workaround

:set paste
https://stackoverflow.com/questions/2514445/turning-off-auto-indent-when-pasting-text-into-vim

**Comment by ogrand** [comment]
Not reproduce
