### ISSUE TITLE
add argo worklow cli

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#88]
As a paas-templates authors
* in order to interact with argo workflows as part of https://github.com/orange-cloudfoundry/paas-templates-private/pull/1020
* I need the argo workflow cli

See instructions at https://github.com/argoproj/argo-workflows/releases/tag/v3.3.1

curl -sLO https://github.com/argoproj/argo-workflows/releases/download/v3.3.1/argo-linux-amd64.gz                           
gunzip argo-linux-amd64.gz       
chmod +x argo-linux-amd64                                                                                                   
sudo mv ./argo-linux-amd64 /usr/local/bin/argo                                                                              
argo version                                                                                                                
argo -h                                                                                                                     
source <(argo completion bash)

**Comment by ogrand** [comment]
Add with latest release
