### ISSUE TITLE
Include terraform operator cli

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/orange-cf-bosh-cli#92]
As we start to use [terraform-operator]( https://github.com/isaaguilar/terraform-operator), we need to include associated cli: [tfo](https://github.com/isaaguilar/terraform-operator-cli) to ease debug. We can use latest version, currently [1.1.2](https://github.com/isaaguilar/terraform-operator-cli/releases/tag/v1.1.2).

**Comment by ogrand** [comment]
Done with latest release
