### ISSUE TITLE
kapp cli refinements

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#97]
Bump cli tools to latest v0.38.0 version

Refine completion
* ytt completion
* kapp completion

Add missing tools
* install kctrl with completion. See 
   * https://carvel.dev/kapp-controller/docs/v0.38.0/install/#installing-kapp-controller-cli-kctrl
   * https://carvel.dev/kapp-controller/docs/v0.38.0/app-command/

**Comment by ogrand** [comment]
Add in latetst release
