### ISSUE TITLE
Add k9s plugin to list suspended kustomization and helmreleases

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/orange-cf-bosh-cli#98]
https://github.com/fluxcd/flux2/discussions/2494#discussioncomment-2877216

> using this plugin, together with the others I submitted months ago and now in default k9s repo, you can press:
> 
>     shift-s to show suspended helmreleases and kustomization
>     shift-t to toggle suspend/resume a specific resource
>     shift-r to force a reconcile of the selected resource...
> 

See https://github.com/derailed/k9s/pull/1584/files

**Comment by ogrand** [comment]
Added to the latest release
